name: Deploy Laravel 11

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Run migrations
        run: php artisan migrate

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: |
          composer install \
            --no-interaction \
            --optimize-autoloader \
            --no-dev

      - name: Install NPM & build assets
        run: |
          npm ci
          npm run build

      - name: Run migrations
        run: php artisan migrate

      - name: Cache config & routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache

      - name: Fix permissions
        run: |
          sudo chown -R www-data:www-data /var/www/hmtl/jeys_dtr
          sudo chmod -R 775 /var/www/html/jeys_dtr/storage \
                            /var/www/html/jeys_dtr/bootstrap/cache

      - name: Clear caches
        run: |
          php artisan cache:clear
          php artisan queue:restart
